package com.fachrudin.project.module.base.events

/**
 * @author achmad.fachrudin
 * @date 21-Nov-18
 */
enum class Pagination {
    LOGIN,
    MAIN_PAGE,
    REGISTER,
    VERIFICATION,
    ACCEPTANCE,
    ORDER_MANAGEMENT,
    OFF_SHELF_LISTING_MANAGEMENT,
    ON_SHELF_LISTING_MANAGEMENT,
    DIGITAL_PRODUCT,
    ADD_PRODUCT,
    EDIT_PRODUCT,
    PAID_ORDER,
    ALL_ORDER,
    PLACED_ORDER,
    SHIPPED_ORDER,
    COMPLETED_ORDER,
    CLOSED_ORDER,
    ORDER_DETAIL,
    SHIPPING,
    WITHDRAWAL,
    CASHBACK,
    CHAT_LIST,
    CHAT_DETAIL,
    SEARCH_PRODUCT,
    SEARCH_STORE,
    WEB_VIEW,
    SEARCH_PAGE,
    STORE,
    CART,
    MESSAGE,
    PRODUCT_DETAIL,
    MAP,
    FEEDBACK,
    PAYMENT_BILLING,
    TCASH_DASHBOARD,
    TCASH_ACTIVATION,
    TCASH_WEBVIEW
}